### ISSUE TITLE
The region of the server metabucket must be configurable

### ISSUE THREAD

**Issue by aead** [minio/minsql#94]
Currently the region of the meta bucket of the server is not configurable. Therefore, you cannot start MinSQL with a server meta bucket that does not match the (somehow) hard-coded value in [`meta.rs`](https://github.com/minio/minsql/blob/master/src/meta.rs#L56)

Anyway, `name` does not seem to be a "good" identifier for specifying the region - in general.

**Comment by harshavardhana** [comment]
We should fetch this automatically using getBucketLocation there is no reason to enable this as configurable value.

**Comment by aead** [comment]
I was not able to get this to work with e.g. `play` until I fixed the code locally. Kept failing with `invalid region error` returned from the S3 server...

**Comment by harshavardhana** [comment]
That is because minio-rs still doesn't implement getBucketLocation I guess

**Comment by harshavardhana** [comment]
You may be right we may need this configurable, since meta bucket is perhaps created automatically by MinSQL so a region param is needed.
